# Generated by Django 2.1 on 2018-10-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('restaurant_id', models.IntegerField()),
                ('menu_items_fi', models.TextField()),
                ('menu_items_en', models.TextField()),
                ('menu_date', models.DateTimeField()),
            ],
        ),
    ]
