# Generated by Django 2.1 on 2018-10-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
