# Generated by Django 2.1 on 2018-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20181003_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_items_en',
            new_name='menu_item_en',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_items_fi',
            new_name='menu_item_fi',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(),
        ),
    ]
